import type { NextPage } from "next";
import Head from "next/head";
import Rankings from "../components/Rankings";
import { useRouter } from "next/router";
import pokemon from "../data/pokemon";
import ssbu from "../data/ssbu";

const slugs as any = {
  pokemon,
  ssbu,
};

const RankingPage: NextPage = () => {
  const router = useRouter();
  const { slug } = router.query as string;

  if (!slug) return null;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Rankings data={slugs[slug]} />
    </div>
  );
};

export default RankingPage;
