import type { NextPage } from 'next'
import Head from 'next/head'
import Rankings from '../components/Rankings'
import data from '../data/data'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Rankings data={data}/>
    </div>
  )
}

export default Home;